[build]
builder = "DOCKERFILE"
dockerfilePath = "Backend/Dockerfile"
dockerContext = "Backend"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar app.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
